// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WRbeJXqGE7dM6J4AnzkvadEe4Dqcht4',
    appId: '1:1027037029035:web:7274c0b0c9bba6493e4dee',
    messagingSenderId: '1027037029035',
    projectId: 'formgenerator-dd6ad',
    authDomain: 'formgenerator-dd6ad.firebaseapp.com',
    storageBucket: 'formgenerator-dd6ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjd9CaZiQKgh54oF6rkAPrEwxHaoKBuU',
    appId: '1:1027037029035:android:aa4590dde405a37b3e4dee',
    messagingSenderId: '1027037029035',
    projectId: 'formgenerator-dd6ad',
    storageBucket: 'formgenerator-dd6ad.appspot.com',
  );
}
